import Head from 'next/head'
import type { AppProps } from 'next/app'
import { GlobalStyle } from '../Global/GlobalStyles'

export default function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <GlobalStyle />
      <Head>
        <title>Bears</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
        <link rel='icon' href='/src/public/favicon.ico' />
      </Head>
      <Component {...pageProps} />
    </>
  )
}
